### ISSUE TITLE
我接入了Google Gamil SDK ,我要开发邮箱App。

### ISSUE THREAD

**Issue by TYUpya** [selenide-examples/gmail#2]
我接入了Google Gamil SDK ,我要开发邮箱App。
但是我写的Demo在当我调用Api接口时提示我需要谷歌服务，会跳转到谷歌商店去。 但是像QQ邮箱和小米邮箱都是直接跳转到网页去让用户登录授权，而且根本不用安装谷歌服务框架。
请问这是怎么实现的？

**Comment by asolntsev** [comment]
@TYUpya Sorry, I don't understand Chineese. Don't understand your question. :(
