### ISSUE TITLE
assertUserCanSeeSentEmails() was  failed 

### ISSUE THREAD

**Issue by geelaro** [selenide-examples/gmail#3]
```
private void assertUserCanSeeSentEmails() {
    $(byText("Sent")).click();
    highlight($(byText("GeeCon demo")).shouldBe(visible));
  }
```
The mail has been sent , but the testcase was failed. 
Test results was "Actual value: visible:false"。

**Comment by asolntsev** [comment]
@geelaro It's ok because GMail UI is constantly being changed. I will try to update my tests accordingly.
